version: "3.3"

services:
  backend:
    build: ./backend
    container_name: plagiarismdetector-backend
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - OPENAI_APIKEY=${OPENAI_APIKEY}
      - GEMINI_APIKEY=${GEMINI_APIKEY}
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_API_URL_TEXT_GENERATE=${BACKEND_API_URL_TEXT_GENERATE}
      - BACKEND_API_URL_TEXT_REPHRASE=${BACKEND_API_URL_TEXT_REPHRASE}
      - BACKEND_API_URL_PDF_GENERATE=${BACKEND_API_URL_PDF_GENERATE}
      - BACKEND_API_URL_PDF_REPHRASE=${BACKEND_API_URL_PDF_REPHRASE}
    volumes:
      - ./backend:/app
      - ./nginx_logs:/var/log/nginx  # 🔥 將容器內的 log 掛載到本機
    working_dir: /app
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    networks:
      - plagiarism-detector-network
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: backend.log

  frontend:
    build:
      context: ./frontend/react_ui
      args:
        FRONTEND_PORT: ${FRONTEND_PORT}
        VITE_API_URL_BACKEND: ${VITE_API_URL_BACKEND}
        VITE_API_URL_TEXT_REPHRASED: ${VITE_API_URL_TEXT_REPHRASED}
        VITE_API_URL_TEXT_GENERATED: ${VITE_API_URL_TEXT_GENERATED}
        VITE_API_URL_PDF_REPHRASED: ${VITE_API_URL_PDF_REPHRASED}
        VITE_API_URL_PDF_GENERATED: ${VITE_API_URL_PDF_GENERATED}
    container_name: plagiarismdetector-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - ./nginx_logs:/var/log/nginx  # 🔥 將容器內的 log 掛載到本機
    env_file:
      - .env
    networks:
      - plagiarism-detector-network
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: frontend.log

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - plagiarism-detector-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_PUBLICBASEURL=http://140.115.54.123:5601  # 👈 就加這行
    networks:
      - plagiarism-detector-network

  fluentd:
    build: ./fluentd
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./nginx_logs:/fluentd/nginxlog:ro  # 🔥 提供 log 給 fluentd
    networks:
      - plagiarism-detector-network


volumes:
  static_volume:

networks:
  plagiarism-detector-network:
